// Exp LUT module — hardware-accurate exp(x) for softmax
//
// Algorithm (matches ExpLutHelper.cs exactly):
//   y = x * LOG2E                          // convert to log2 domain
//   n = floor(y)                           // integer part → IEEE 754 exponent
//   f = y - n                              // fractional part ∈ [0,1)
//   2^f ≈ BRAM[floor(f*(LUT_SIZE-1))]     // LUT lookup
//       + frac * (BRAM[i+1] - BRAM[i])    // linear interpolation
//   result = 2^n * 2^f                     // combine: set exponent field
//
// Special cases:
//   NaN input    → 0.0
//   n < -126     → 0.0  (underflow)
//   n >  127     → 0x7F800000 (infinity clamp; caller should range-limit inputs)
//
// Pipeline: 4 stages
//   Stage 1: multiply by LOG2E, detect NaN
//   Stage 2: floor → n; f = y-n; compute LUT index t = f*(LUT_SIZE-1)
//   Stage 3: BRAM read (index i = floor(t)); capture frac = t-i
//   Stage 4: interpolate 2^f; combine with 2^n
//
// Parameters:
//   LUT_SIZE  — number of BRAM entries (256 or 512); must match init file
//   LUT_FILE  — path to $readmemh init hex file (generated by C# FpgaExpLutVecGen)
//
// Ports:
//   clk        — clock
//   rst        — synchronous active-high reset
//   en         — pipeline enable
//   x_fp32     — 32-bit FP32 input
//   valid_in   — qualify input
//   result_fp32 — 32-bit FP32 output (4 cycles later)
//   valid_out  — qualifies output

`timescale 1ns/1ps

module exp_lut #(
    parameter int          LUT_SIZE = 256,
    parameter string       LUT_FILE = "exp_lut_init.hex"
)(
    input  logic        clk,
    input  logic        rst,
    input  logic        en,

    input  logic [31:0] x_fp32,
    input  logic        valid_in,

    output logic [31:0] result_fp32,
    output logic        valid_out
);

    // -----------------------------------------------------------------------
    // LOG2E constant as FP32 bits: 1.44269504 ≈ 0x3FB8AA3B
    // -----------------------------------------------------------------------
    localparam logic [31:0] LOG2E_BITS = 32'h3FB8AA3B;

    // -----------------------------------------------------------------------
    // BRAM ROM — LUT_SIZE × 32-bit entries
    // Stores 2^(i/(LUT_SIZE-1)) for i=0..LUT_SIZE-1
    // lut[0] = 1.0 (2^0), lut[LUT_SIZE-1] = 2.0 (2^1)
    // -----------------------------------------------------------------------
    logic [31:0] lut_rom [0:LUT_SIZE-1];
    initial $readmemh(LUT_FILE, lut_rom);

    // -----------------------------------------------------------------------
    // Pipeline signals
    // -----------------------------------------------------------------------

    // Stage 1
    shortreal s1_y;
    logic     s1_nan;
    logic     s1_v;

    // Stage 2
    int       s2_n;
    shortreal s2_f;
    shortreal s2_t;
    int       s2_idx;
    shortreal s2_frac;
    logic     s2_nan;
    logic     s2_v;

    // Stage 3
    logic [31:0] s3_lut0;
    logic [31:0] s3_lut1;
    shortreal    s3_frac;
    int          s3_n;
    logic        s3_nan;
    logic        s3_v;

    // Stage 4
    shortreal s4_pow2f;
    int       s4_n;
    logic     s4_nan;
    logic     s4_v;

    // Combinational temporaries (used inside always_ff — declared at module scope)
    shortreal tmp_sr_x;
    shortreal tmp_y;
    int       tmp_ni;
    shortreal tmp_fi;
    shortreal tmp_ti;
    int       tmp_idxi;
    shortreal tmp_l0, tmp_l1, tmp_p2f;
    logic [31:0] tmp_pow2n_bits;
    shortreal    tmp_result_sr;

    // -----------------------------------------------------------------------
    // Stage 1: multiply x * LOG2E, detect NaN
    // -----------------------------------------------------------------------
    shortreal sr_log2e;
    always_comb sr_log2e = $bitstoshortreal(LOG2E_BITS);

    always_ff @(posedge clk) begin
        if (rst) begin
            s1_v <= 0;
        end else if (en) begin
            tmp_sr_x = $bitstoshortreal(x_fp32);
            s1_y    <= tmp_sr_x * sr_log2e;
            s1_nan  <= (x_fp32[30:23] == 8'hFF) && (x_fp32[22:0] != 0);
            s1_v    <= valid_in;
        end
    end

    // -----------------------------------------------------------------------
    // Stage 2: floor → n, f = y-n, LUT index, interpolation weight
    // -----------------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            s2_v <= 0;
        end else if (en) begin
            tmp_y    = s1_y;
            // $floor() is the only reliable floor in XSim — int'(shortreal) rounds to nearest
            tmp_ni   = int'($floor(real'(tmp_y)));
            tmp_fi   = tmp_y - shortreal'(tmp_ni);
            if (tmp_fi < 0.0) tmp_fi = 0.0;
            if (tmp_fi > 1.0) tmp_fi = 1.0;

            tmp_ti   = tmp_fi * shortreal'(LUT_SIZE - 1);
            tmp_idxi = int'($floor(real'(tmp_ti)));
            if (tmp_idxi >= LUT_SIZE - 1) tmp_idxi = LUT_SIZE - 2;

            s2_n    <= tmp_ni;
            s2_f    <= tmp_fi;
            s2_t    <= tmp_ti;
            s2_idx  <= tmp_idxi;
            s2_frac <= tmp_ti - shortreal'(tmp_idxi);
            s2_nan  <= s1_nan;
            s2_v    <= s1_v;
        end
    end

    // -----------------------------------------------------------------------
    // Stage 3: BRAM read
    // -----------------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            s3_v <= 0;
        end else if (en) begin
            s3_lut0 <= lut_rom[s2_idx];
            s3_lut1 <= lut_rom[s2_idx + 1];
            s3_frac <= s2_frac;
            s3_n    <= s2_n;
            s3_nan  <= s2_nan;
            s3_v    <= s2_v;
        end
    end

    // -----------------------------------------------------------------------
    // Stage 4: linear interpolation of 2^f, combine with 2^n
    // -----------------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            s4_v <= 0;
        end else if (en) begin
            tmp_l0   = $bitstoshortreal(s3_lut0);
            tmp_l1   = $bitstoshortreal(s3_lut1);
            s4_pow2f <= tmp_l0 + s3_frac * (tmp_l1 - tmp_l0);
            s4_n     <= s3_n;
            s4_nan   <= s3_nan;
            s4_v     <= s3_v;
        end
    end

    // -----------------------------------------------------------------------
    // Output combinational
    // -----------------------------------------------------------------------
    always_comb begin
        if (s4_nan || s4_n < -126) begin
            result_fp32 = 32'h0000_0000;
        end else if (s4_n > 127) begin
            result_fp32 = 32'h7F80_0000;
        end else begin
            tmp_pow2n_bits = {1'b0, 8'(s4_n + 127), 23'h0};
            tmp_result_sr  = $bitstoshortreal(tmp_pow2n_bits) * s4_pow2f;
            result_fp32    = $shortrealtobits(tmp_result_sr);
        end
        valid_out = s4_v;
    end

endmodule
