// fp32_div.sv -- Synthesizable IEEE 754 FP32 scalar division: result = a / b
//
// Algorithm: 256-entry recip ROM seed + 2x Newton-Raphson iterations for 1/b,
//            then final fp32_mul: result = a x (1/b)
// NR step:   r_new = r x (2 - b x r)
//
// Latency: ~30 cycles fixed
//   IDLE(1) + SEED(1) + PREP(1) + [NR1: 3+4+3] + [NR2: 3+4+3] + MUL(3) + DONE(1)
//
// ROM: recip_rom.hex -- 256x FP32 seeds, one per line
//   Index: b_mant[22:15]  (top 8 mantissa bits, 256 entries)
//   Entry: FP32 of 1/xq  where xq = bitstofloat((127<<23) | (idx<<15))
//   Generated by FpgaDivVecGen.WriteRomHex()
//
// Special cases (IEEE 754 compliant):
//   NaN input       -> quiet NaN (0x7FC00000)
//   Inf / Inf       -> quiet NaN
//   0 / 0           -> quiet NaN
//   finite / 0      -> +-Inf
//   0 / finite      -> +-0
//   Inf / finite    -> +-Inf
//   finite / Inf    -> +-0
//
// All signals at module scope -- no automatic/local variables in always_ff.
// C# reference: (float)((double)a / (double)b)
// XSim tolerance: VsSoftwareRelTol = 0.01%
// Target: Xilinx ZCU102 (UltraScale+ XCZU9EG), Vivado 2023.x

`timescale 1ns/1ps
module fp32_div (
    input  logic        clk,
    input  logic        rst,
    input  logic        valid_in,
    input  logic [31:0] a_fp32,
    input  logic [31:0] b_fp32,
    output logic [31:0] result_fp32,
    output logic        valid_out
);

    // -- 256-entry recip seed ROM --------------------------------------------
    // rom_style="block" forces RAMB36E2 inference (not LUT RAM).
    // recip_rom.hex must be registered in Vivado sources:
    //   add_files -fileset sources_1 recip_rom.mem
    //   set_property file_type {Memory Initialization Files} [get_files recip_rom.mem]
    (* rom_style = "block" *) logic [31:0] recip_rom [0:255];
    initial $readmemh("recip_rom.mem", recip_rom);

    // -- fp32_mul instance ---------------------------------------------------
    logic        mul_valid_in;
    logic [31:0] mul_a, mul_b, mul_result;
    logic        mul_valid_out;

    fp32_mul u_mul (
        .clk      (clk),
        .rst      (rst),
        .valid_in (mul_valid_in),
        .a        (mul_a),
        .b        (mul_b),
        .result   (mul_result),
        .valid_out(mul_valid_out)
    );

    // -- fp32_add instance ---------------------------------------------------
    logic        add_valid_in;
    logic [31:0] add_a, add_b, add_result;
    logic        add_valid_out;

    fp32_add u_add (
        .clk      (clk),
        .rst      (rst),
        .valid_in (add_valid_in),
        .a        (add_a),
        .b        (add_b),
        .result   (add_result),
        .valid_out(add_valid_out)
    );

    // -- FSM states ----------------------------------------------------------
    localparam logic [3:0]
        S_IDLE    = 4'd0,
        S_SEED    = 4'd1,
        S_PREP    = 4'd2,
        S_SPECIAL = 4'd3,
        S_NR1_S1  = 4'd4,
        S_NR1_S2  = 4'd5,
        S_NR1_S3  = 4'd6,
        S_NR2_S1  = 4'd7,
        S_NR2_S2  = 4'd8,
        S_NR2_S3  = 4'd9,
        S_MUL     = 4'd10,
        S_DONE    = 4'd11;

    logic [3:0] state;
    logic       op_launched;

    // -- Input latches -------------------------------------------------------
    logic [31:0] a_lat;
    logic [31:0] b_lat;

    // -- Decomposition latches -----------------------------------------------
    logic [7:0]  lat_rom_idx;
    logic [7:0]  lat_b_biased_exp;
    logic        lat_a_nan, lat_b_nan;
    logic        lat_a_inf, lat_b_inf;
    logic        lat_a_zero, lat_b_zero;
    logic [31:0] lat_special_result;

    // -- NR working register -------------------------------------------------
    logic [31:0] r;
    logic [31:0] t_reg;

    // -- FP32 constants ------------------------------------------------------
    localparam logic [31:0] FP32_2P0  = 32'h40000000;
    localparam logic [31:0] FP32_QNAN = 32'h7FC00000;
    localparam logic [31:0] FP32_ZERO = 32'h00000000;

    // -- Combinatorial wires for S_PREP seed exponent correction -------------
    // recip(b) = (1/m_b) * 2^(-e_b)
    // scaled_bexp = seed_bexp + 127 - b_biased_exp
    logic [7:0]        w_seed_bexp;
    logic signed [9:0] w_seed_bexp_s;
    logic signed [9:0] w_b_bexp_s;
    logic [7:0]        w_scaled_bexp;

    assign w_seed_bexp   = recip_rom[lat_rom_idx][30:23];
    assign w_seed_bexp_s = 10'(signed'({1'b0, w_seed_bexp}));
    assign w_b_bexp_s    = 10'(signed'({1'b0, lat_b_biased_exp}));
    assign w_scaled_bexp = 8'(w_seed_bexp_s + 10'sd127 - w_b_bexp_s);

    // -- FSM -----------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            state              <= S_IDLE;
            op_launched        <= 1'b0;
            valid_out          <= 1'b0;
            mul_valid_in       <= 1'b0;
            add_valid_in       <= 1'b0;
            result_fp32        <= FP32_ZERO;
            r                  <= FP32_ZERO;
            t_reg              <= FP32_ZERO;
            a_lat              <= FP32_ZERO;
            b_lat              <= FP32_ZERO;
            mul_a              <= FP32_ZERO;
            mul_b              <= FP32_ZERO;
            add_a              <= FP32_ZERO;
            add_b              <= FP32_ZERO;
            lat_rom_idx        <= 8'h0;
            lat_b_biased_exp   <= 8'h0;
            lat_a_nan          <= 1'b0;
            lat_b_nan          <= 1'b0;
            lat_a_inf          <= 1'b0;
            lat_b_inf          <= 1'b0;
            lat_a_zero         <= 1'b0;
            lat_b_zero         <= 1'b0;
            lat_special_result <= FP32_ZERO;
        end else begin
            mul_valid_in <= 1'b0;
            add_valid_in <= 1'b0;
            valid_out    <= 1'b0;

            case (state)
                S_IDLE: begin
                    if (valid_in) begin
                        a_lat <= a_fp32;
                        b_lat <= b_fp32;
                        state <= S_SEED;
                    end
                end

                S_SEED: begin
                    lat_rom_idx      <= b_lat[22:15];
                    lat_b_biased_exp <= b_lat[30:23];
                    lat_a_nan  <= (a_lat[30:23] == 8'hFF) && (a_lat[22:0] != 23'h0);
                    lat_b_nan  <= (b_lat[30:23] == 8'hFF) && (b_lat[22:0] != 23'h0);
                    lat_a_inf  <= (a_lat[30:23] == 8'hFF) && (a_lat[22:0] == 23'h0);
                    lat_b_inf  <= (b_lat[30:23] == 8'hFF) && (b_lat[22:0] == 23'h0);
                    lat_a_zero <= (a_lat[30:23] == 8'h00);
                    lat_b_zero <= (b_lat[30:23] == 8'h00);
                    state      <= S_PREP;
                end

                S_PREP: begin
                    if (lat_a_nan || lat_b_nan ||
                        (lat_a_inf  && lat_b_inf)  ||
                        (lat_a_zero && lat_b_zero)) begin
                        lat_special_result <= FP32_QNAN;
                        state              <= S_SPECIAL;
                    end else if ((lat_b_zero && !lat_a_zero) ||
                                 (lat_a_inf  && !lat_b_inf)) begin
                        lat_special_result <= {a_lat[31] ^ b_lat[31], 8'hFF, 23'h0};
                        state              <= S_SPECIAL;
                    end else if ((lat_a_zero && !lat_b_zero) ||
                                 (lat_b_inf  && !lat_a_inf)) begin
                        lat_special_result <= {a_lat[31] ^ b_lat[31], 31'h0};
                        state              <= S_SPECIAL;
                    end else begin
                        // seed: sign of 1/b = sign of b
                        r           <= {b_lat[31], w_scaled_bexp,
                                        recip_rom[lat_rom_idx][22:0]};
                        op_launched <= 1'b0;
                        state       <= S_NR1_S1;
                    end
                end

                S_SPECIAL: begin
                    result_fp32 <= lat_special_result;
                    valid_out   <= 1'b1;
                    state       <= S_IDLE;
                end

                // -- NR1: r = r * (2 - b*r) ----------------------------------
                S_NR1_S1: begin
                    if (!op_launched) begin
                        mul_a        <= b_lat;
                        mul_b        <= r;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        t_reg       <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR1_S2;
                    end
                end

                S_NR1_S2: begin
                    if (!op_launched) begin
                        add_a        <= FP32_2P0;
                        add_b        <= {~t_reg[31], t_reg[30:0]};
                        add_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (add_valid_out) begin
                        t_reg       <= add_result;
                        op_launched <= 1'b0;
                        state       <= S_NR1_S3;
                    end
                end

                S_NR1_S3: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= t_reg;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        r           <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S1;
                    end
                end

                // -- NR2: r = r * (2 - b*r) ----------------------------------
                S_NR2_S1: begin
                    if (!op_launched) begin
                        mul_a        <= b_lat;
                        mul_b        <= r;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        t_reg       <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S2;
                    end
                end

                S_NR2_S2: begin
                    if (!op_launched) begin
                        add_a        <= FP32_2P0;
                        add_b        <= {~t_reg[31], t_reg[30:0]};
                        add_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (add_valid_out) begin
                        t_reg       <= add_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S3;
                    end
                end

                S_NR2_S3: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= t_reg;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        r           <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_MUL;
                    end
                end

                // -- Final: result = a * (1/b) --------------------------------
                S_MUL: begin
                    if (!op_launched) begin
                        mul_a        <= a_lat;
                        mul_b        <= r;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        result_fp32 <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_DONE;
                    end
                end

                S_DONE: begin
                    valid_out <= 1'b1;
                    state     <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule