// FP32 reciprocal square root: result = 1/sqrt(x)  (combinatorial)
//
// Algorithm: 512-entry seed ROM + 2x Newton-Raphson iterations.
//   NR step: r = r * (1.5 - 0.5*x*r*r)  using shortreal multiply
//
// ROM indexing (matches ExpLutHelper.BuildRecipSqrtRom exactly):
//   index = {expLsb, mant[22:15]}     (9-bit, 512 entries)
//   expLsb = unbiasedExp[0]           (parity of unbiased exponent)
//   expLsb=0: representant in [1,2)   biased exp = 127
//   expLsb=1: representant in [2,4)   biased exp = 128
//
// Exponent correction after ROM lookup (exact power of 2, no FP multiply):
//   scale = 2^(-(unbiasedExp - expLsb)/2)
//   (unbiasedExp - expLsb) is always even by construction.
//
// ROM hex file: recipsqrt_rom.hex — 512 lines of FP32 hex.
//   Generated by C# FpgaRecipSqrtVecGen.WriteRomHex() from ExpLutHelper internals.
//   Written to xsim_work/ before each XSim run; loaded via $readmemh.
//
// Synthesizable: only shortreal multiplies + ROM — no $sqrt().
// XSim tolerance: VsSoftwareRelTol = 0.01% (XSimCollection.cs).
// C# reference: ExpLutHelper.RecipSqrt(float x)

`timescale 1ns/1ps

module fp32_sqrt (
    input  logic [31:0] x_fp32,
    output logic [31:0] result_fp32
);

    // ── 512-entry seed ROM (FP32 values stored as 32-bit logic) ──────────────
    logic [31:0] seed_rom [0:511];
    initial $readmemh("recipsqrt_rom.hex", seed_rom);

    // ── Combinatorial datapath ────────────────────────────────────────────────
    logic        [7:0]  exp8_biased;
    logic signed [8:0]  exp8_s;       // unbiased, 9-bit signed
    logic               expLsb;
    logic        [7:0]  mant_top8;
    logic        [8:0]  rom_idx;
    logic signed [8:0]  half_adj;
    logic        [7:0]  adj_exp;
    logic        [31:0] scale_bits;
    shortreal           x_sr, r_seed, r, half_x, scale;

    always_comb begin
        x_sr = $bitstoshortreal(x_fp32);

        // ── Decompose ─────────────────────────────────────────────────────────
        exp8_biased = x_fp32[30:23];
        exp8_s      = 9'(signed'({1'b0, exp8_biased})) - 9'sd127;
        expLsb      = exp8_s[0];
        mant_top8   = x_fp32[22:15];
        rom_idx     = {expLsb, mant_top8};

        // ── ROM seed → shortreal ──────────────────────────────────────────────
        r_seed = $bitstoshortreal(seed_rom[rom_idx]);

        // ── Exponent correction: multiply r_seed by 2^half_adj ───────────────
        // half_adj = -(exp8_s - expLsb) / 2  (exact integer, no rounding)
        half_adj  = -(exp8_s - 9'(signed'({8'b0, expLsb}))) >>> 1;
        adj_exp   = 8'(half_adj + 9'sd127);
        scale_bits = {1'b0, adj_exp, 23'b0};
        scale = $bitstoshortreal(scale_bits);
        r     = r_seed * scale;

        // ── Newton-Raphson iteration 1 ────────────────────────────────────────
        half_x = 0.5 * x_sr;
        r = r * (1.5 - half_x * r * r);

        // ── Newton-Raphson iteration 2 ────────────────────────────────────────
        r = r * (1.5 - half_x * r * r);

        result_fp32 = $shortrealtobits(r);
    end

endmodule
