// fp32_sqrt.sv ? Synthesizable IEEE 754 FP32 reciprocal square root: result = 1/sqrt(x)
//
// Algorithm: 9-bit ROM seed (512 entries) + 2x Newton-Raphson iterations
// NR step:   r_new = r * (1.5 - 0.5*x*r*r)
//
// Latency: ~31 cycles fixed
//   IDLE(1) + SEED(1) + PREP(1) + [NR1: 3+3+4+3] + [NR2: 3+3+4+3] + DONE(1)
//
// ROM: recipsqrt_rom.hex -- 512x FP32 seeds as 32-bit hex
//   Index: {unbiasedExp[0], mant[22:15]}   (9-bit, 512 entries)
//   Exponent correction: integer add to seed biased-exponent field (no FP multiply needed)
//   Generated by C# FpgaRecipSqrtVecGen.WriteRomHex() / ExpLutHelper.BuildRecipSqrtRom()
//
// Special cases (IEEE 754 compliant):
//   x = 0 or subnormal -> +Inf  (0x7F800000)
//   x < 0              -> quiet NaN (0x7FC00000)
//   x = +Inf           -> +0    (0x00000000)
//   x = NaN            -> quiet NaN (0x7FC00000)
//
// All signals at module scope -- no automatic/local variables in always_ff.
// C# reference: ExpLutHelper.RecipSqrt(float x)
// XSim tolerance: VsSoftwareRelTol = 0.01% (XSimCollection.cs)
// Target: Xilinx ZCU102 (UltraScale+ XCZU9EG), Vivado 2023.x

`timescale 1ns/1ps
module fp32_sqrt (
    input  logic        clk,
    input  logic        rst,
    input  logic        valid_in,
    input  logic [31:0] x_fp32,
    output logic [31:0] result_fp32,
    output logic        valid_out
);

    // -- 512-entry seed ROM --------------------------------------------------
    // rom_style="block" forces RAMB36E2 inference (not LUT RAM).
    // recipsqrt_rom.hex must be registered in Vivado sources:
    //   add_files -fileset sources_1 recipsqrt_rom.mem
    //   set_property file_type {Memory Initialization Files} [get_files recipsqrt_rom.mem]
    (* rom_style = "block" *) logic [31:0] seed_rom [0:511];
    initial $readmemh("recipsqrt_rom.mem", seed_rom);

    // -- fp32_mul instance ---------------------------------------------------
    logic        mul_valid_in;
    logic [31:0] mul_a, mul_b, mul_result;
    logic        mul_valid_out;

    fp32_mul u_mul (
        .clk      (clk),
        .rst      (rst),
        .valid_in (mul_valid_in),
        .a        (mul_a),
        .b        (mul_b),
        .result   (mul_result),
        .valid_out(mul_valid_out)
    );

    // -- fp32_add instance ---------------------------------------------------
    logic        add_valid_in;
    logic [31:0] add_a, add_b, add_result;
    logic        add_valid_out;

    fp32_add u_add (
        .clk      (clk),
        .rst      (rst),
        .valid_in (add_valid_in),
        .a        (add_a),
        .b        (add_b),
        .result   (add_result),
        .valid_out(add_valid_out)
    );

    // -- FSM states ----------------------------------------------------------
    localparam logic [3:0]
        S_IDLE    = 4'd0,
        S_SEED    = 4'd1,
        S_PREP    = 4'd2,
        S_SPECIAL = 4'd3,
        S_NR1_S1  = 4'd4,
        S_NR1_S2  = 4'd5,
        S_NR1_S3  = 4'd6,
        S_NR1_S4  = 4'd7,
        S_NR2_S1  = 4'd8,
        S_NR2_S2  = 4'd9,
        S_NR2_S3  = 4'd10,
        S_NR2_S4  = 4'd11,
        S_DONE    = 4'd12;

    logic [3:0] state;
    logic       op_launched;

    // -- Input latch ---------------------------------------------------------
    logic [31:0] x_lat;

    // -- Decomposition latches (filled in S_SEED from x_lat) -----------------
    logic [8:0]        lat_rom_idx;
    logic signed [8:0] lat_half_adj;
    logic              lat_is_nan;
    logic              lat_is_inf;
    logic              lat_is_zero;
    logic              lat_is_denorm;
    logic              lat_is_neg;
    logic [31:0]       lat_half_x;

    // -- NR working registers ------------------------------------------------
    logic [31:0] r;
    logic [31:0] r_sq;
    logic [31:0] hx_rsq;
    logic [31:0] special_result;

    // -- FP32 constants ------------------------------------------------------
    localparam logic [31:0] FP32_1P5  = 32'h3FC00000;
    localparam logic [31:0] FP32_QNAN = 32'h7FC00000;
    localparam logic [31:0] FP32_INF  = 32'h7F800000;
    localparam logic [31:0] FP32_ZERO = 32'h00000000;

    // -- Combinatorial wires for S_SEED (derived from x_lat) -----------------
    // Declared at module scope to avoid automatic variables in always_ff.
    logic [7:0]        w_biased_exp;
    logic signed [8:0] w_unbiased_exp;
    logic              w_exp_lsb;
    logic signed [8:0] w_exp_minus_lsb;
    logic signed [8:0] w_half_adj;

    assign w_biased_exp    = x_lat[30:23];
    assign w_unbiased_exp  = 9'(signed'({1'b0, w_biased_exp})) - 9'sd127;
    assign w_exp_lsb       = w_unbiased_exp[0];
    assign w_exp_minus_lsb = w_unbiased_exp - 9'(signed'({8'b0, w_exp_lsb}));
    assign w_half_adj      = (-w_exp_minus_lsb) >>> 1;

    // -- Combinatorial wires for S_PREP (derived from latched values) ---------
    logic [7:0]        w_seed_bexp;
    logic signed [8:0] w_seed_bexp_s;
    logic [7:0]        w_scaled_bexp;

    assign w_seed_bexp   = seed_rom[lat_rom_idx][30:23];
    assign w_seed_bexp_s = 9'(signed'({1'b0, w_seed_bexp}));
    assign w_scaled_bexp = 8'(w_seed_bexp_s + lat_half_adj);

    // -- FSM -----------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            state          <= S_IDLE;
            op_launched    <= 1'b0;
            valid_out      <= 1'b0;
            mul_valid_in   <= 1'b0;
            add_valid_in   <= 1'b0;
            result_fp32    <= FP32_ZERO;
            r              <= FP32_ZERO;
            r_sq           <= FP32_ZERO;
            hx_rsq         <= FP32_ZERO;
            special_result <= FP32_ZERO;
            mul_a          <= FP32_ZERO;
            mul_b          <= FP32_ZERO;
            add_a          <= FP32_ZERO;
            add_b          <= FP32_ZERO;
            x_lat          <= FP32_ZERO;
            lat_rom_idx    <= 9'h0;
            lat_half_adj   <= 9'sh0;
            lat_is_nan     <= 1'b0;
            lat_is_inf     <= 1'b0;
            lat_is_zero    <= 1'b0;
            lat_is_denorm  <= 1'b0;
            lat_is_neg     <= 1'b0;
            lat_half_x     <= FP32_ZERO;
        end else begin
            mul_valid_in <= 1'b0;
            add_valid_in <= 1'b0;
            valid_out    <= 1'b0;

            case (state)
                // -- Wait for transaction ------------------------------------
                S_IDLE: begin
                    if (valid_in) begin
                        x_lat <= x_fp32;
                        state <= S_SEED;
                    end
                end

                // -- Decompose x_lat; latch rom_idx, half_adj, specials ------
                // Combinatorial wires w_* (assign above) are stable here.
                S_SEED: begin
                    lat_rom_idx  <= {w_exp_lsb, x_lat[22:15]};
                    lat_half_adj <= w_half_adj;
                    lat_is_nan   <= (w_biased_exp == 8'hFF) && (x_lat[22:0] != 23'h0);
                    lat_is_inf   <= (w_biased_exp == 8'hFF) && (x_lat[22:0] == 23'h0);
                    lat_is_zero  <= (w_biased_exp == 8'h00) && (x_lat[22:0] == 23'h0);
                    lat_is_denorm<= (w_biased_exp == 8'h00) && (x_lat[22:0] != 23'h0);
                    lat_is_neg   <= x_lat[31];
                    lat_half_x   <= (w_biased_exp == 8'h00)
                                    ? FP32_ZERO
                                    : {x_lat[31], w_biased_exp - 8'd1, x_lat[22:0]};
                    state        <= S_PREP;
                end

                // -- Synchronous ROM read; compute r_initial ------------------
                // w_seed_bexp / w_scaled_bexp (assign wires) are valid here
                // because lat_rom_idx and lat_half_adj are already latched.
                S_PREP: begin
                    if (lat_is_nan || (lat_is_neg && !lat_is_zero)) begin
                        special_result <= FP32_QNAN;
                        state          <= S_SPECIAL;
                    end else if (lat_is_inf) begin
                        special_result <= FP32_ZERO;
                        state          <= S_SPECIAL;
                    end else if (lat_is_zero || lat_is_denorm) begin
                        special_result <= FP32_INF;
                        state          <= S_SPECIAL;
                    end else begin
                        r           <= {seed_rom[lat_rom_idx][31],
                                        w_scaled_bexp,
                                        seed_rom[lat_rom_idx][22:0]};
                        op_launched <= 1'b0;
                        state       <= S_NR1_S1;
                    end
                end

                S_SPECIAL: begin
                    result_fp32 <= special_result;
                    valid_out   <= 1'b1;
                    state       <= S_IDLE;
                end

                // -- NR1 step 1: r_sq = r * r --------------------------------
                S_NR1_S1: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= r;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        r_sq        <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR1_S2;
                    end
                end

                // -- NR1 step 2: hx_rsq = lat_half_x * r_sq -----------------
                S_NR1_S2: begin
                    if (!op_launched) begin
                        mul_a        <= lat_half_x;
                        mul_b        <= r_sq;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        hx_rsq      <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR1_S3;
                    end
                end

                // -- NR1 step 3: coef = 1.5 + (-hx_rsq) ---------------------
                S_NR1_S3: begin
                    if (!op_launched) begin
                        add_a        <= FP32_1P5;
                        add_b        <= {~hx_rsq[31], hx_rsq[30:0]};
                        add_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (add_valid_out) begin
                        hx_rsq      <= add_result;
                        op_launched <= 1'b0;
                        state       <= S_NR1_S4;
                    end
                end

                // -- NR1 step 4: r = r * coef --------------------------------
                S_NR1_S4: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= hx_rsq;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        r           <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S1;
                    end
                end

                // -- NR2 step 1: r_sq = r * r --------------------------------
                S_NR2_S1: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= r;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        r_sq        <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S2;
                    end
                end

                // -- NR2 step 2: hx_rsq = lat_half_x * r_sq -----------------
                S_NR2_S2: begin
                    if (!op_launched) begin
                        mul_a        <= lat_half_x;
                        mul_b        <= r_sq;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        hx_rsq      <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S3;
                    end
                end

                // -- NR2 step 3: coef = 1.5 + (-hx_rsq) ---------------------
                S_NR2_S3: begin
                    if (!op_launched) begin
                        add_a        <= FP32_1P5;
                        add_b        <= {~hx_rsq[31], hx_rsq[30:0]};
                        add_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (add_valid_out) begin
                        hx_rsq      <= add_result;
                        op_launched <= 1'b0;
                        state       <= S_NR2_S4;
                    end
                end

                // -- NR2 step 4: result = r * coef ---------------------------
                S_NR2_S4: begin
                    if (!op_launched) begin
                        mul_a        <= r;
                        mul_b        <= hx_rsq;
                        mul_valid_in <= 1'b1;
                        op_launched  <= 1'b1;
                    end
                    if (mul_valid_out) begin
                        result_fp32 <= mul_result;
                        op_launched <= 1'b0;
                        state       <= S_DONE;
                    end
                end

                S_DONE: begin
                    valid_out <= 1'b1;
                    state     <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule