// LayerNorm forward pass — per-token row normalisation
//
// Algorithm (matches LayerNorm.Forward() / ExpLutHelper.RecipSqrt exactly):
//   For each token row i of D FP32 values:
//     μ      = (1/D) · Σ x[d]
//     σ²     = (1/D) · Σ (x[d] − μ)²
//     invStd = fp32_sqrt( σ² + ε )       // combinatorial, instantiated here
//     y[d]   = γ[d] · (x[d] − μ) · invStd + β[d]
//
// FSM (one token row per activation):
//   IDLE    — wait for start pulse; latch x[], gamma[], beta[]
//   SUM_X   — D cycles: accumulate running sum Σx[d] using shortreal add
//   MEAN    — 1 cycle: divide by D (multiply by inv_D constant)
//   SUM_VAR — D cycles: second pass, accumulate Σ(x[d]-μ)², reuse x_buf
//   VAR     — 1 cycle: divide by D → σ²; feed σ²+ε to fp32_sqrt (combinatorial)
//   SCALE   — D cycles: y[d] = γ[d]*(x[d]-μ)*invStd + β[d]
//   OUTPUT  — 1 cycle: assert out_valid
//
// fp32_sqrt is combinatorial (instantiated inline); result is available the same
// cycle the VAR state executes — no extra latency.
//
// recipsqrt_rom.hex must be present in xsim_work/ before simulation.
// Generated by FpgaRecipSqrtVecGen.WriteRomHex().
//
// C# reference: LayerNorm.Forward() using ExpLutHelper.RecipSqrt()
// Tolerance: VsSoftwareRelTol = 0.01% (XSimCollection.cs)
//
// Parameters:
//   D       — embed dimension (number of values per token row)
//
// Interface:
//   x_in    — D packed FP32 inputs  [D*32-1:0], valid on start cycle
//   gamma   — D packed FP32 scale   [D*32-1:0], valid on start cycle
//   beta    — D packed FP32 shift   [D*32-1:0], valid on start cycle
//   start   — 1-cycle pulse to begin one token row
//   y_out   — D packed FP32 outputs [D*32-1:0], valid when out_valid=1
//   out_valid — 1-cycle pulse when y_out is ready

`timescale 1ns/1ps

module layernorm #(
    parameter int D = 4
)(
    input  logic clk,
    input  logic rst,
    input  logic en,

    input  logic [D*32-1:0] x_in,
    input  logic [D*32-1:0] gamma,
    input  logic [D*32-1:0] beta,
    input  logic             start,

    output logic [D*32-1:0] y_out,
    output logic             out_valid
);

    // ε = 1e-5 as FP32 bits
    localparam logic [31:0] EPS_BITS = 32'h3727C5AC; // 1e-5

    // inv_D = 1/D as shortreal (precomputed; D is a parameter)
    // For D=4: 1/4 = 0.25 = 32'h3E800000
    localparam shortreal INV_D = 1.0 / D;

    // ── fp32_sqrt instance (combinatorial 1/√x) ──────────────────────────────
    logic [31:0] sqrt_in_bits;
    logic [31:0] sqrt_out_bits;

    fp32_sqrt u_sqrt (
        .x_fp32     (sqrt_in_bits),
        .result_fp32(sqrt_out_bits)
    );

    // ── Internal storage ──────────────────────────────────────────────────────
    logic [31:0] x_buf    [0:D-1];
    logic [31:0] gamma_buf[0:D-1];
    logic [31:0] beta_buf [0:D-1];
    logic [31:0] y_reg    [0:D-1];

    // Pack y_reg → y_out
    always_comb
        for (int d = 0; d < D; d++)
            y_out[d*32 +: 32] = y_reg[d];

    // ── FSM ───────────────────────────────────────────────────────────────────
    typedef enum logic [2:0] {
        IDLE,
        SUM_X,
        MEAN,
        SUM_VAR,
        VAR,
        SCALE,
        OUTPUT
    } state_t;

    state_t      state;
    int unsigned cnt;

    shortreal sum_acc;   // running accumulator for mean / variance
    shortreal mean_sr;   // registered mean
    // invStd is read combinatorially from sqrt_out_bits in SCALE state;
    // var_plus_eps is registered in VAR and stable for all D SCALE cycles.

    // Wire fp32_sqrt input from registered σ²+ε (set in VAR state)
    shortreal var_plus_eps;
    assign sqrt_in_bits = $shortrealtobits(var_plus_eps);

    always_ff @(posedge clk) begin
        if (rst) begin
            state         <= IDLE;
            cnt           <= 0;
            out_valid     <= 1'b0;
            sum_acc       <= 0.0;
            mean_sr       <= 0.0;
            var_plus_eps  <= 0.0;
            for (int d = 0; d < D; d++) begin
                x_buf    [d] <= '0;
                gamma_buf[d] <= '0;
                beta_buf [d] <= '0;
                y_reg    [d] <= '0;
            end
        end else if (en) begin
            out_valid <= 1'b0;

            case (state)

                // ── Wait for start ────────────────────────────────────────
                IDLE: begin
                    if (start) begin
                        for (int d = 0; d < D; d++) begin
                            x_buf    [d] <= x_in  [d*32 +: 32];
                            gamma_buf[d] <= gamma [d*32 +: 32];
                            beta_buf [d] <= beta  [d*32 +: 32];
                        end
                        sum_acc <= 0.0;
                        cnt     <= 0;
                        state   <= SUM_X;
                    end
                end

                // ── Pass 1: accumulate Σx[d] ─────────────────────────────
                SUM_X: begin
                    sum_acc <= sum_acc + $bitstoshortreal(x_buf[cnt]);
                    cnt     <= cnt + 1;
                    if (cnt == D - 1) begin
                        cnt   <= 0;
                        state <= MEAN;
                    end
                end

                // ── Compute mean = sum * (1/D) ────────────────────────────
                MEAN: begin
                    mean_sr <= sum_acc * INV_D;
                    sum_acc <= 0.0;
                    cnt     <= 0;
                    state   <= SUM_VAR;
                end

                // ── Pass 2: accumulate Σ(x[d]-μ)² ────────────────────────
                SUM_VAR: begin
                    begin
                        shortreal diff;
                        diff    = $bitstoshortreal(x_buf[cnt]) - mean_sr;
                        sum_acc <= sum_acc + diff * diff;
                    end
                    cnt <= cnt + 1;
                    if (cnt == D - 1) begin
                        cnt   <= 0;
                        state <= VAR;
                    end
                end

                // ── Compute σ² = sum*(1/D), feed σ²+ε to fp32_sqrt ───────
                // fp32_sqrt is combinatorial; result available same cycle.
                VAR: begin
                    begin
                        shortreal var_sr, eps_sr;
                        var_sr       = sum_acc * INV_D;
                        eps_sr       = $bitstoshortreal(EPS_BITS);
                        var_plus_eps <= var_sr + eps_sr;
                        // sqrt_out_bits is already driven combinatorially from var_plus_eps.
                        // We register invstd next cycle after var_plus_eps propagates.
                        // → use a 1-cycle SCALE entry to latch invstd.
                    end
                    cnt   <= 0;
                    state <= SCALE;
                end

                // ── Pass 3: y[d] = γ[d]*(x[d]-μ)*invStd + β[d] ──────────
                // sqrt_out_bits is combinatorial from var_plus_eps (stable since VAR state).
                SCALE: begin
                    begin
                        shortreal xd, gd, bd, diff, invstd, y;
                        invstd = $bitstoshortreal(sqrt_out_bits); // combinatorial, stable
                        xd     = $bitstoshortreal(x_buf    [cnt]);
                        gd     = $bitstoshortreal(gamma_buf[cnt]);
                        bd     = $bitstoshortreal(beta_buf [cnt]);
                        diff   = xd - mean_sr;
                        y      = gd * (diff * invstd) + bd;
                        y_reg[cnt] <= $shortrealtobits(y);
                    end
                    cnt <= cnt + 1;
                    if (cnt == D - 1) begin
                        cnt   <= 0;
                        state <= OUTPUT;
                    end
                end

                // ── Assert out_valid for one cycle ────────────────────────
                OUTPUT: begin
                    out_valid <= 1'b1;
                    state     <= IDLE;
                end

            endcase
        end
    end

endmodule
