# synth_rom_test.tcl -- Batch Vivado synthesis test for fp32_sqrt ROM initialization.
#
# Purpose:
#   Verify that initial $readmemh("recipsqrt_rom.mem") correctly infers RAMB18E2/RAMB36E2
#   and produces no Synth 8-2898 warnings on the selected target part.
#
# Usage:
#   vivado -mode batch -source synth_rom_test.tcl
#   (run from the neuro-fabric-fpga/scripts/ directory, or pass full paths below)
#
# Outputs (written to ./synth_rom_test_out/):
#   utilization.rpt  -- check for RAMB18E2/RAMB36E2 rows
#   timing.rpt       -- informational
#   vivado.log       -- check for Synth 8-2898 / CRITICAL WARNING / ERROR

set script_dir [file dirname [file normalize [info script]]]
set rtl_dir    [file join $script_dir "../rtl"]
set out_dir    [file join $script_dir "synth_rom_test_out"]

file mkdir $out_dir

# ── Create in-memory project (non-project mode avoids .xpr clutter) ──────────
set_part xczu7eg-ffvc1156-2-e

# ── Add RTL sources ───────────────────────────────────────────────────────────
# fp32_mul and fp32_add are dependencies of fp32_sqrt
read_verilog -sv [file join $rtl_dir "fp32_mul.sv"]
read_verilog -sv [file join $rtl_dir "fp32_add.sv"]
read_verilog -sv [file join $rtl_dir "fp32_sqrt.sv"]
read_verilog -sv [file join $script_dir "synth_rom_test_top.sv"]

# ── Register the ROM .mem file as Memory Initialization File ─────────────────
# This is required so Vivado resolves the $readmemh path during synthesis.
# Without this, synthesis may emit: [Synth 8-2898] ignoring could not open $readmem data file
set mem_file [file join $out_dir "recipsqrt_rom.mem"]

# Copy the mem file (generated by C# WriteRomHex) from xsim_work to out_dir
# so it sits next to the synthesis run directory.
#
# Search order:
#   1) NEURO_TESTVECS env var override
#   2) sibling repo path: ../../neuro-fabric/run/fpga-testvecs
if {[file exists $mem_file]} {
    file delete -force $mem_file
}

if {[info exists ::env(NEURO_TESTVECS)] && $::env(NEURO_TESTVECS) ne ""} {
    set testvecs_root [file normalize $::env(NEURO_TESTVECS)]
} else {
    set testvecs_root [file normalize [file join $script_dir "../../neuro-fabric/run/fpga-testvecs"]]
}

set xsim_mem [file join $testvecs_root "fp32_sqrt/xsim_work/recipsqrt_rom.mem"]
if {[file exists $xsim_mem]} {
    file copy -force $xsim_mem $out_dir
    puts "INFO: Copied recipsqrt_rom.mem from $xsim_mem"
} else {
    error "recipsqrt_rom.mem not found at $xsim_mem. Run RecipSqrtTests first or set NEURO_TESTVECS."
}

read_mem $mem_file
set_property file_type {Memory Initialization Files} [get_files $mem_file]

# ── Synthesize ────────────────────────────────────────────────────────────────
synth_design -top synth_rom_test_top -part xczu7eg-ffvc1156-2-e -mode out_of_context

# ── Reports ───────────────────────────────────────────────────────────────────
report_utilization    -file [file join $out_dir "utilization.rpt"]
report_timing_summary -file [file join $out_dir "timing.rpt"] -max_paths 5

puts ""
puts "================================================================"
puts " SYNTHESIS COMPLETE — check these in $out_dir:"
puts "================================================================"
puts " utilization.rpt -- look for RAMB18E2 or RAMB36E2 count >= 1"
puts " timing.rpt      -- informational"
puts " vivado.log      -- grep for: Synth 8-2898 | CRITICAL | ERROR"
puts "================================================================"
